theme = "bogster"

[editor]
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
C-s = ":write"
C-o = "file_picker"
F12 = "goto_definition"
pageup = "page_cursor_half_up"
pagedown = "page_cursor_half_down"
S-up = "move_line_up"
S-down = "move_line_down"
A-left = "goto_previous_buffer"
A-right = "goto_next_buffer"
C-f = "search"
A-up = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
A-down = ["extend_to_line_bounds", "delete_selection", "paste_after"]
S-right = "move_next_word_start"
S-left = "move_prev_word_end"
S-g = "goto_file_end"
